version: '3'

volumes:
  local_mysql_backup: {}

services:
  mysql:
    build:
      context: .
      dockerfile: MySql/Dockerfile
    image: mysql_server
    container_name: mysql_server
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - local_mysql_backup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'wagstaff'
      MYSQL_PASSWORD: 'mypass'
      MYSQL_DATABASE: 'wagstaff_INFOST_410'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  python3:
    build:
      context: .
      dockerfile: Python3.6/Dockerfile
    image: ubuntu
    container_name: ubuntu
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      - ../script_files:/script_files
    command: /start

networks:
    backend:
        # use the bridge driver, but enable IPv6
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"

    frontend:
        # use the bridge driver, but enable IPv6
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"