#!/bin/bash
source py36env/bin/activate

python3 /script_files/execute_sql_script.py

cd /script_files/txt2pdf/
python3 txt2pdf.py SQL_assignment_1_script_output.txt
rm /script_files/txt2pdf/SQL_assignment_1_script_output.txt